#!/usr/bin/env python3
"""Aggregate Asset Formation Map v0 across fixed five Battles."""
import glob
import json
from pathlib import Path

DAYS = (0, 8, 12, 16, 20)

def mean(xs):
    return sum(xs) / len(xs) if xs else None

def get_cp(raw, day):
    for c in raw["checkpoints"]:
        if int(c["day"]) == day and int(c["hour"]) == 0:
            return c
    raise KeyError((raw["seed"], day))

def main():
    paths = sorted(Path(p) for p in glob.glob(
        "asset-formation-artifacts/**/asset_formation_map_v0_*.json",
        recursive=True,
    ))
    if len(paths) != 5:
        raise SystemExit(f"Expected 5 artifacts, found {len(paths)}")
    raws = [json.loads(p.read_text(encoding="utf-8")) for p in paths]
    types = list(raws[0]["checkpoints"][0]["self"]["summary_by_type"].keys())

    fields = [
        "present_asset_count",
        "held_output_units",
        "current_harvestable_units",
        "harvest_eligible_asset_count",
        "near_window_asset_count",
        "near_window_public_opportunity_count",
        "near_window_base_units_conditional",
        "future_to_day20_public_opportunity_count",
        "future_to_day20_base_units_conditional",
    ]

    map_by_day = {}
    for day in DAYS:
        day_out = {"land": {}, "assets": {}}
        for lf in [
            "unlocked_quadrant_count",
            "unlocked_tile_count",
            "empty_unlocked_tile_count",
            "productive_occupied_tile_count",
        ]:
            sv = [float(get_cp(r, day)["self"]["land"][lf]) for r in raws]
            ov = [float(get_cp(r, day)["opponent"]["land"][lf]) for r in raws]
            day_out["land"][lf] = {
                "self_absolute_mean": mean(sv),
                "opponent_absolute_mean": mean(ov),
                "mean_residual_opponent_minus_self": mean([o-s for s,o in zip(sv,ov)]),
            }

        for typ in types:
            day_out["assets"][typ] = {}
            for field in fields:
                sv = [float(get_cp(r, day)["self"]["summary_by_type"][typ][field]) for r in raws]
                ov = [float(get_cp(r, day)["opponent"]["summary_by_type"][typ][field]) for r in raws]
                day_out["assets"][typ][field] = {
                    "self_absolute_mean": mean(sv),
                    "opponent_absolute_mean": mean(ov),
                    "mean_residual_opponent_minus_self": mean([o-s for s,o in zip(sv,ov)]),
                }
        map_by_day[str(day)] = day_out

    # Interval changes are pure differences of the coarse World map.
    interval_changes = {}
    for a, b in zip(DAYS[:-1], DAYS[1:]):
        key = f"{a}->{b}"
        interval_changes[key] = {"land": {}, "assets": {}}
        for lf in map_by_day[str(a)]["land"]:
            ra = map_by_day[str(a)]["land"][lf]["mean_residual_opponent_minus_self"]
            rb = map_by_day[str(b)]["land"][lf]["mean_residual_opponent_minus_self"]
            interval_changes[key]["land"][lf] = rb - ra
        for typ in types:
            interval_changes[key]["assets"][typ] = {}
            for field in fields:
                ra = map_by_day[str(a)]["assets"][typ][field]["mean_residual_opponent_minus_self"]
                rb = map_by_day[str(b)]["assets"][typ][field]["mean_residual_opponent_minus_self"]
                interval_changes[key]["assets"][typ][field] = rb - ra

    cases = []
    for r in raws:
        cases.append({
            "seed": r["seed"],
            "seat": r["seat"],
            "terminal": r["terminal"],
        })

    payload = {
        "schema": "kaggriculture.strong-origin-v2.asset-formation-map.result.v0",
        "battle_count": 5,
        "checkpoint_days": list(DAYS),
        "terminal_absolute": {
            "mean_self": mean([float(c["terminal"]["self"]) for c in cases]),
            "mean_opponent": mean([float(c["terminal"]["opponent"]) for c in cases]),
            "mean_margin": mean([float(c["terminal"]["margin"]) for c in cases]),
        },
        "map_by_day": map_by_day,
        "interval_residual_changes": interval_changes,
        "cases": cases,
        "environment_provenance_unique": list({
            json.dumps(r["environment_provenance"], sort_keys=True)
            for r in raws
        }),
        "boundary": [
            "All cross-Battle summaries are absolute means per side plus opponent-minus-self residual.",
            "No unlike asset types are summed into one quantity or value score.",
            "Interval residual changes are descriptive World-map differences only.",
            "Near/future fields remain conditional public opportunities as labeled in raw observations.",
            "No Action diagnosis, causal interpretation, Candidate, ranking, or adoption conclusion is generated by this aggregator.",
        ],
    }
    Path("asset_formation_map_v0_result.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    compact = {
        "terminal_absolute": payload["terminal_absolute"],
        "days": {
            d: {
                typ: {
                    "present": map_by_day[str(d)]["assets"][typ]["present_asset_count"],
                    "harvestable": map_by_day[str(d)]["assets"][typ]["current_harvestable_units"],
                    "near4_conditional": map_by_day[str(d)]["assets"][typ]["near_window_base_units_conditional"],
                }
                for typ in types
            }
            for d in DAYS
        },
        "interval_present_asset_residual_changes": {
            k: {typ: v["assets"][typ]["present_asset_count"] for typ in types}
            for k, v in interval_changes.items()
        },
    }
    print("ASSET_FORMATION_MAP_RESULT " + json.dumps(compact, ensure_ascii=False, separators=(",", ":")))

if __name__ == "__main__":
    main()
